
version: '3.8'

services:
  swarmpit:
    image: swarmpit/swarmpit:1.9.0 # Ganti dengan versi stabil terbaru yang Anda inginkan
    ports:
      - "3000:8080" # UI SwarmPit
    environment:
      - SWARMPIT_DB=couchdb://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
      # - SWARMPIT_APP_SECRET=gantiDenganSecretAcakYangPanjang # Opsional: untuk keamanan sesi yang lebih baik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarmpit-net
    depends_on:
      - db
      - influxdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"] # Atau endpoint health API Swarmpit jika ada
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  db:
    image: couchdb:2.3.0 # Pertimbangkan untuk menggunakan versi yang lebih baru jika kompatibel
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - swarmpit-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  influxdb:
    image: influxdb:1.8 # Pertimbangkan untuk menggunakan versi yang lebih baru jika kompatibel
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=swarmpit
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      # - INFLUXDB_HTTP_AUTH_ENABLED=true # Aktifkan jika Anda ingin semua akses HTTP memerlukan otentikasi
    networks:
      - swarmpit-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  agent:
    image: swarmpit/agent:latest # Sebaiknya ganti dengan versi spesifik yang stabil
    environment:
      - DOCKER_API_VERSION=1.35 # Periksa apakah versi ini masih relevan untuk lingkungan Anda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - swarmpit-net
    deploy:
      mode: global # Agen biasanya dijalankan di semua node atau node pekerja
      # placement:
      #   constraints: [node.role == worker] # Jika hanya ingin di worker

networks:
  swarmpit-net:
    driver: overlay

volumes:
  db-data:
  influxdb-data:
