version: '3.8'

services:
  agent:
    image: portainer/agent:latest
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global  # deploy ke semua node
      placement:
        constraints: [node.platform.os == linux]

networks:
  agent_network:
    driver: overlay
