version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dimsuser
      POSTGRES_DB: dimsdb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - pg_password
    deploy:
      placement:
        constraints:
          - node.hostname == master-orchestra

  nginx_branch1:
    image: nginx:alpine
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == brance-1
    ports:
      - target: 80
        published: 8081
        mode: host

  nginx_branch2:
    image: nginx:alpine
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == branch-2
    ports:
      - target: 80
        published: 8082
        mode: host

volumes:
  pgdata:

secrets:
  pg_password:
    external: true
